/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: 'class',
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.js',
    ],
    theme: {
        extend: {
            colors: {
                'primary':                    '#00236f',
                'primary-container':          '#1e3a8a',
                'on-primary':                 '#ffffff',
                'on-primary-container':       '#90a8ff',
                'primary-fixed':              '#dce1ff',
                'primary-fixed-dim':          '#b6c4ff',
                'on-primary-fixed':           '#00164e',
                'on-primary-fixed-variant':   '#264191',
                'inverse-primary':            '#b6c4ff',
                'secondary':                  '#006a61',
                'secondary-container':        '#86f2e4',
                'on-secondary':               '#ffffff',
                'on-secondary-container':     '#006f66',
                'secondary-fixed':            '#89f5e7',
                'secondary-fixed-dim':        '#6bd8cb',
                'on-secondary-fixed':         '#00201d',
                'on-secondary-fixed-variant': '#005049',
                'tertiary':                   '#272b2d',
                'tertiary-container':         '#3d4143',
                'on-tertiary':                '#ffffff',
                'on-tertiary-container':      '#aaadaf',
                'tertiary-fixed':             '#e0e3e5',
                'tertiary-fixed-dim':         '#c4c7c9',
                'on-tertiary-fixed':          '#191c1e',
                'on-tertiary-fixed-variant':  '#444749',
                'error':                      '#ba1a1a',
                'error-container':            '#ffdad6',
                'on-error':                   '#ffffff',
                'on-error-container':         '#93000a',
                'background':                 '#f8f9ff',
                'on-background':              '#0d1c2e',
                'surface':                    '#f8f9ff',
                'surface-dim':                '#ccdbf3',
                'surface-bright':             '#f8f9ff',
                'surface-variant':            '#d5e3fc',
                'surface-container-lowest':   '#ffffff',
                'surface-container-low':      '#eff4ff',
                'surface-container':          '#e6eeff',
                'surface-container-high':     '#dce9ff',
                'surface-container-highest':  '#d5e3fc',
                'surface-tint':               '#4059aa',
                'on-surface':                 '#0d1c2e',
                'on-surface-variant':         '#444651',
                'outline':                    '#757682',
                'outline-variant':            '#c5c5d3',
                'inverse-surface':            '#233144',
                'inverse-on-surface':         '#eaf1ff',
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg:      '0.5rem',
                xl:      '0.75rem',
                '2xl':   '1rem',
                full:    '9999px',
            },
            spacing: {
                xs:             '4px',
                sm:             '8px',
                md:             '16px',
                lg:             '24px',
                xl:             '32px',
                '2xl':          '48px',
                gutter:         '24px',
                base:           '4px',
                'container-max':'1280px',
            },
            fontFamily: {
                sans:       ['"Public Sans"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
                'h1':       ['"Public Sans"'],
                'h2':       ['"Public Sans"'],
                'h3':       ['"Public Sans"'],
                'body-lg':  ['"Public Sans"'],
                'body-md':  ['"Public Sans"'],
                'body-sm':  ['"Public Sans"'],
                'label-md': ['"Public Sans"'],
                'label-sm': ['"Public Sans"'],
            },
            fontSize: {
                'h1':       ['36px', { lineHeight: '1.2', fontWeight: '700' }],
                'h2':       ['30px', { lineHeight: '1.3', fontWeight: '600' }],
                'h3':       ['24px', { lineHeight: '1.3', fontWeight: '600' }],
                'body-lg':  ['18px', { lineHeight: '1.6', fontWeight: '400' }],
                'body-md':  ['16px', { lineHeight: '1.5', fontWeight: '400' }],
                'body-sm':  ['14px', { lineHeight: '1.5', fontWeight: '400' }],
                'label-md': ['14px', { lineHeight: '1',   fontWeight: '600' }],
                'label-sm': ['12px', { lineHeight: '1',   fontWeight: '500' }],
            },
        },
    },
    plugins: [],
};
